package com.tch.test.springboot.model.three;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbg.generated Sat Sep 30 10:52:58 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.name
     *
     * @mbg.generated Sat Sep 30 10:52:58 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbg.generated Sat Sep 30 10:52:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbg.generated Sat Sep 30 10:52:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.name
     *
     * @return the value of organization.name
     *
     * @mbg.generated Sat Sep 30 10:52:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.name
     *
     * @param name the value for organization.name
     *
     * @mbg.generated Sat Sep 30 10:52:58 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}